# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 18:29
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backscratcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_description', models.TextField()),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_size', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], default='M', max_length=2), size=None)),
            ],
            options={
                'ordering': ('item_name',),
            },
        ),
    ]
